part of s;

// Generated by flutter_l10n. Do not edit it.
class $intl_zh extends S {
  const $intl_zh();

  @override
  TextDirection get textDirection => TextDirection.ltr;

  @override
  String get username => r'用户名';

  @override
  String get password => r'密码';

  @override
  String get register => r'注册';

  @override
  String get item => r'列表项';
}
