part of s;

// Generated by flutter_l10n. Do not edit it.
class $intl_en extends S {
  const $intl_en();

  @override
  TextDirection get textDirection => TextDirection.ltr;

  @override
  String get username => r'username';

  @override
  String get password => r'password';

  @override
  String get register => r'register';

  @override
  String get item => r'item';
}
