library s;

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

part 'intl_zh.dart';
part 'intl_en.dart';

// Generated by flutter_l10n. Do not edit it.
class S implements WidgetsLocalizations {
  const S();

  @override
  TextDirection get textDirection => TextDirection.ltr;

  static S of(BuildContext context) => Localizations.of<S>(context, S);

  static const LocalizationsDelegate<S> delegate = _Delegate();

  String get username => r'用户名';

  String get password => r'密码';

  String get register => r'注册';

  String get item => r'列表项';
}

class _Delegate extends LocalizationsDelegate<S> {
  const _Delegate();

  @override
  Future<S> load(Locale locale) {
    String tag = locale.countryCode == null || locale.countryCode.isEmpty
        ? locale.languageCode
        : locale.toString();
    switch (tag) {
      case 'intl_zh':
        return SynchronousFuture<S>(const $intl_zh());
      case 'intl_en':
        return SynchronousFuture<S>(const $intl_en());
    }
    return SynchronousFuture<S>(const S());
  }

  @override
  bool isSupported(Locale locale) => true;

  @override
  bool shouldReload(_Delegate old) => false;
}
